Fiddling with this actually breaks PL/Parrot. Let's not do that.
Messing with CPPFLAGS gives this error when running the tests:

1..2
ERROR:  incompatible library "/Users/leto/git/postgresql/contrib/plparrot/libplparrot.so": missing magic block
HINT:  Extension libraries are required to use the PG_MODULE_MAGIC macro.